site_name: ReportPlus
site_url: https://eljoelopez.github.io/ReportPlus

theme:
  name: material
  locale: en
  highlightjs: true

markdown_extensions:
  toc:
    permalink: true
  admonition: {}


nav:
 - Home: index.md
 - Report: generated.md
